"""Formatter for AI Code Review results.

This module handles the conversion of structured ReviewResult objects
into human-readable Markdown comments for GitHub.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ai_reviewer.core.models import (
    TaskAlignmentStatus,
    VulnerabilitySeverity,
)

if TYPE_CHECKING:
    from ai_reviewer.core.models import ReviewResult

# Icons for severity levels (strict style)
SEVERITY_ICONS = {
    VulnerabilitySeverity.CRITICAL: "🔴",
    VulnerabilitySeverity.HIGH: "🟠",
    VulnerabilitySeverity.MEDIUM: "🟡",
    VulnerabilitySeverity.LOW: "🔵",
    VulnerabilitySeverity.INFO: "ℹ️",  # noqa: RUF001
}

# Icons for task alignment
ALIGNMENT_ICONS = {
    TaskAlignmentStatus.ALIGNED: "✅",
    TaskAlignmentStatus.MISALIGNED: "❌",
    TaskAlignmentStatus.INSUFFICIENT_DATA: "⚠️",
}


def format_review_comment(result: ReviewResult) -> str:
    """Format review result as a Markdown comment.

    Args:
        result: The structured review result.

    Returns:
        Markdown string ready for posting to GitHub.
    """
    parts = ["# AI Code Review Report"]

    # 1. Summary
    parts.append("## Summary")
    parts.append(result.summary)

    # 2. Security Analysis
    parts.append("\n## Security Analysis")
    if not result.vulnerabilities:
        parts.append("✅ No critical vulnerabilities found.")
    else:
        parts.append("| Severity | Issue | Description | Recommendation |")
        parts.append("| :--- | :--- | :--- | :--- |")

        for vuln in result.vulnerabilities:
            icon = SEVERITY_ICONS.get(vuln.severity, "❓")
            severity_str = f"{icon} **{vuln.severity.value.upper()}**"

            # Format location if available
            location = ""
            if vuln.file:
                location = f"<br>_File: {vuln.file}"
                if vuln.line:
                    location += f":{vuln.line}"
                location += "_"

            # Escape pipes in content to avoid breaking table
            title = vuln.title.replace("|", "\\|")
            desc = vuln.description.replace("|", "\\|")
            rec = vuln.recommendation.replace("|", "\\|")

            parts.append(f"| {severity_str} | {title}{location} | {desc} | {rec} |")

    # 3. Task Alignment
    parts.append("\n## Task Alignment")
    alignment_icon = ALIGNMENT_ICONS.get(result.task_alignment, "❓")
    alignment_status = result.task_alignment.value.replace("_", " ").title()

    parts.append(f"**Status:** {alignment_icon} {alignment_status}")

    if result.task_alignment_reasoning:
        parts.append(f"\n{result.task_alignment_reasoning}")

    # Footer
    parts.append("\n---\n_Generated by AI Code Reviewer_")

    return "\n".join(parts)
