"""Parser and generator for ``.reviewbot.md`` project configuration.

The ``.reviewbot.md`` file lives in the repository root and provides
human-editable overrides for the Discovery pipeline. When present,
Discovery reads it and skips most of the automated pipeline.

The parser is tolerant: missing sections or unknown fields are silently
ignored, making it safe to use with hand-edited files.
"""

from __future__ import annotations

import re

from ai_reviewer.discovery.models import (
    AutomatedChecks,
    PlatformData,
    ProjectProfile,
    ReviewGuidance,
)

# ── Regex helpers ────────────────────────────────────────────────────

_SECTION_RE = re.compile(r"^##\s+(.+)$", re.MULTILINE)
_SUBSECTION_RE = re.compile(r"^###\s+(.+)$", re.MULTILINE)
_FIELD_RE = re.compile(r"^-\s+\*\*(.+?):\*\*\s*(.+)$", re.MULTILINE)
_LIST_ITEM_RE = re.compile(r"^-\s+(.+)$", re.MULTILINE)

_HEADER_COMMENT = "<!-- Auto-generated by AI ReviewBot. Feel free to edit. -->"

# ── Section / field heading constants ────────────────────────────────

_H_STACK = "Stack"
_H_AUTOMATED_CHECKS = "Automated Checks"
_H_REVIEW_GUIDANCE = "Review Guidance"

_H_SKIP = "Skip (CI handles these)"
_H_SKIP_SHORT = "Skip"
_H_FOCUS = "Focus"
_H_CONVENTIONS = "Conventions"

_F_LANGUAGE = "Language"
_F_FRAMEWORK = "Framework"
_F_PACKAGE_MANAGER = "Package manager"
_F_LAYOUT = "Layout"
_F_LINTING = "Linting"
_F_FORMATTING = "Formatting"
_F_TYPE_CHECKING = "Type checking"
_F_TESTING = "Testing"
_F_SECURITY = "Security"
_F_CI = "CI"


# ── Section extraction ───────────────────────────────────────────────


def _get_section(content: str, heading: str) -> str:
    """Extract text between ``## heading`` and the next ``##`` heading.

    Args:
        content: Full markdown content.
        heading: Section heading to find (case-insensitive).

    Returns:
        Section body text, or empty string if not found.
    """
    for m in _SECTION_RE.finditer(content):
        if m.group(1).strip().lower() == heading.lower():
            start = m.end()
            # Find next ## heading
            nxt = _SECTION_RE.search(content, start)
            return content[start : nxt.start() if nxt else len(content)].strip()
    return ""


def _get_subsection(section: str, heading: str) -> str:
    """Extract text between ``### heading`` and the next ``###`` heading.

    Args:
        section: Section body text.
        heading: Subsection heading to find (case-insensitive).

    Returns:
        Subsection body text, or empty string if not found.
    """
    for m in _SUBSECTION_RE.finditer(section):
        if m.group(1).strip().lower() == heading.lower():
            start = m.end()
            nxt = _SUBSECTION_RE.search(section, start)
            return section[start : nxt.start() if nxt else len(section)].strip()
    return ""


def _extract_field(section: str, field_name: str) -> str | None:
    """Extract value of ``- **FieldName:** value`` from a section.

    Args:
        section: Section body text.
        field_name: Field name to look for (case-insensitive).

    Returns:
        Field value string, or ``None`` if not found.
    """
    for m in _FIELD_RE.finditer(section):
        if m.group(1).strip().lower() == field_name.lower():
            return m.group(2).strip()
    return None


def _extract_list_items(text: str) -> tuple[str, ...]:
    """Extract plain list items (non-bold) from text.

    Skips items that match the ``**Key:** value`` pattern.

    Args:
        text: Markdown text containing list items.

    Returns:
        Tuple of stripped list item strings.
    """
    items: list[str] = []
    for m in _LIST_ITEM_RE.finditer(text):
        item = m.group(1).strip()
        if not item.startswith("**"):
            items.append(item)
    return tuple(items)


def _split_tools(value: str | None) -> tuple[str, ...]:
    """Split a comma-separated tool list into a tuple.

    Args:
        value: Comma-separated string, or ``None``.

    Returns:
        Tuple of stripped, non-empty tool names.
    """
    if not value:
        return ()
    return tuple(t.strip() for t in value.split(",") if t.strip())


def _split_language_version(value: str | None) -> tuple[str, str | None]:
    """Split ``"Python 3.13"`` into ``("Python", "3.13")``.

    Args:
        value: Language string, optionally with version.

    Returns:
        Tuple of (language_name, version_or_None).
    """
    if not value:
        return ("Unknown", None)
    parts = value.split(None, 1)
    if len(parts) == 1:
        return (parts[0], None)
    return (parts[0], parts[1])


# ── Parser ───────────────────────────────────────────────────────────


def parse_reviewbot_md(content: str) -> ProjectProfile:
    """Parse a ``.reviewbot.md`` file into a ``ProjectProfile``.

    The parser is tolerant: missing sections or unknown fields are
    silently ignored. Hand-edited files with extra content work fine.

    Args:
        content: Full content of the ``.reviewbot.md`` file.

    Returns:
        A ``ProjectProfile`` populated from the parsed fields.
    """
    stack_section = _get_section(content, _H_STACK)
    checks_section = _get_section(content, _H_AUTOMATED_CHECKS)
    guidance_section = _get_section(content, _H_REVIEW_GUIDANCE)

    # Stack
    lang_raw = _extract_field(stack_section, _F_LANGUAGE)
    primary_language, language_version = _split_language_version(lang_raw)
    framework = _extract_field(stack_section, _F_FRAMEWORK)
    package_manager = _extract_field(stack_section, _F_PACKAGE_MANAGER)
    layout = _extract_field(stack_section, _F_LAYOUT)

    # Automated Checks
    linting = _split_tools(_extract_field(checks_section, _F_LINTING))
    formatting = _split_tools(_extract_field(checks_section, _F_FORMATTING))
    type_checking = _split_tools(_extract_field(checks_section, _F_TYPE_CHECKING))
    testing = _split_tools(_extract_field(checks_section, _F_TESTING))
    security = _split_tools(_extract_field(checks_section, _F_SECURITY))
    ci_provider = _extract_field(checks_section, _F_CI)

    # Guidance
    skip_section = _get_subsection(guidance_section, _H_SKIP)
    if not skip_section:
        skip_section = _get_subsection(guidance_section, _H_SKIP_SHORT)
    focus_section = _get_subsection(guidance_section, _H_FOCUS)
    conventions_section = _get_subsection(guidance_section, _H_CONVENTIONS)

    skip_items = _extract_list_items(skip_section)
    focus_items = _extract_list_items(focus_section)
    convention_items = _extract_list_items(conventions_section)

    return ProjectProfile(
        platform_data=PlatformData(
            languages={primary_language: 100.0},
            primary_language=primary_language,
        ),
        framework=framework,
        language_version=language_version,
        package_manager=package_manager,
        layout=layout,
        automated_checks=AutomatedChecks(
            linting=linting,
            formatting=formatting,
            type_checking=type_checking,
            testing=testing,
            security=security,
            ci_provider=ci_provider,
        ),
        guidance=ReviewGuidance(
            skip_in_review=skip_items,
            focus_in_review=focus_items,
            conventions=convention_items,
        ),
    )


# ── Generator helpers ─────────────────────────────────────────────────


def _generate_checks_section(lines: list[str], ac: AutomatedChecks) -> None:
    """Append the Automated Checks section if any checks exist."""
    check_fields: list[tuple[str, tuple[str, ...] | str | None]] = [
        (_F_LINTING, ac.linting),
        (_F_FORMATTING, ac.formatting),
        (_F_TYPE_CHECKING, ac.type_checking),
        (_F_TESTING, ac.testing),
        (_F_SECURITY, ac.security),
        (_F_CI, ac.ci_provider),
    ]
    if not any(v for _, v in check_fields):
        return
    lines.append("")
    lines.append(f"## {_H_AUTOMATED_CHECKS}")
    for label, value in check_fields:
        if isinstance(value, tuple) and value:
            lines.append(f"- **{label}:** {', '.join(value)}")
        elif isinstance(value, str) and value:
            lines.append(f"- **{label}:** {value}")


def _generate_guidance_section(lines: list[str], g: ReviewGuidance) -> None:
    """Append the Review Guidance section if any guidance exists."""
    if not any([g.skip_in_review, g.focus_in_review, g.conventions]):
        return
    lines.append("")
    lines.append(f"## {_H_REVIEW_GUIDANCE}")
    for heading, items in [
        (_H_SKIP, g.skip_in_review),
        (_H_FOCUS, g.focus_in_review),
        (_H_CONVENTIONS, g.conventions),
    ]:
        if items:
            lines.append("")
            lines.append(f"### {heading}")
            for item in items:
                lines.append(f"- {item}")


# ── Generator ────────────────────────────────────────────────────────


def generate_reviewbot_md(profile: ProjectProfile) -> str:
    """Generate a ``.reviewbot.md`` file from a ``ProjectProfile``.

    Produces a human-readable Markdown file that can be committed to
    the repository root.

    Args:
        profile: The project profile to serialize.

    Returns:
        Markdown string ready to write to ``.reviewbot.md``.
    """
    lines: list[str] = [
        _HEADER_COMMENT,
        "# .reviewbot.md",
        "",
        f"## {_H_STACK}",
    ]

    pd = profile.platform_data
    lang_str = pd.primary_language
    if profile.language_version:
        lang_str += f" {profile.language_version}"
    lines.append(f"- **{_F_LANGUAGE}:** {lang_str}")

    for label, value in [
        (_F_FRAMEWORK, profile.framework),
        (_F_PACKAGE_MANAGER, profile.package_manager),
        (_F_LAYOUT, profile.layout),
    ]:
        if value:
            lines.append(f"- **{label}:** {value}")

    _generate_checks_section(lines, profile.automated_checks)
    _generate_guidance_section(lines, profile.guidance)

    lines.append("")  # trailing newline
    return "\n".join(lines)


__all__ = [
    "generate_reviewbot_md",
    "parse_reviewbot_md",
]
