"""Tests for discovery.reviewbot_config — .reviewbot.md parser/generator."""

from __future__ import annotations

import pytest

from ai_reviewer.discovery.models import (
    AutomatedChecks,
    PlatformData,
    ProjectProfile,
    ReviewGuidance,
)
from ai_reviewer.discovery.reviewbot_config import (
    generate_reviewbot_md,
    parse_reviewbot_md,
)

# ── Fixtures ─────────────────────────────────────────────────────────

FULL_REVIEWBOT_MD = """\
<!-- Auto-generated by AI ReviewBot. Feel free to edit. -->
# .reviewbot.md

## Stack
- **Language:** Python 3.13
- **Framework:** Django 5.1
- **Package manager:** uv
- **Layout:** src

## Automated Checks
- **Linting:** ruff
- **Formatting:** ruff format
- **Type checking:** mypy --strict
- **Testing:** pytest (coverage >= 80%)
- **Security:** bandit
- **CI:** GitHub Actions

## Review Guidance

### Skip (CI handles these)
- Code formatting and import ordering
- Basic type errors

### Focus
- Security (no SAST in CI)
- Business logic correctness

### Conventions
- Conventional commits
- Google-style docstrings
"""

MINIMAL_REVIEWBOT_MD = """\
# .reviewbot.md

## Stack
- **Language:** Go
"""


# ── TestParseReviewbotMd ─────────────────────────────────────────────


class TestParseReviewbotMd:
    """Tests for parse_reviewbot_md."""

    def test_full_parse_stack(self) -> None:
        profile = parse_reviewbot_md(FULL_REVIEWBOT_MD)
        assert profile.platform_data.primary_language == "Python"
        assert profile.language_version == "3.13"
        assert profile.framework == "Django 5.1"
        assert profile.package_manager == "uv"
        assert profile.layout == "src"

    def test_full_parse_automated_checks(self) -> None:
        profile = parse_reviewbot_md(FULL_REVIEWBOT_MD)
        ac = profile.automated_checks
        assert ac.linting == ("ruff",)
        assert ac.formatting == ("ruff format",)
        assert ac.type_checking == ("mypy --strict",)
        assert ac.testing == ("pytest (coverage >= 80%)",)
        assert ac.security == ("bandit",)
        assert ac.ci_provider == "GitHub Actions"

    def test_full_parse_guidance(self) -> None:
        profile = parse_reviewbot_md(FULL_REVIEWBOT_MD)
        g = profile.guidance
        assert "Code formatting and import ordering" in g.skip_in_review
        assert "Basic type errors" in g.skip_in_review
        assert "Security (no SAST in CI)" in g.focus_in_review
        assert "Business logic correctness" in g.focus_in_review
        assert "Conventional commits" in g.conventions
        assert "Google-style docstrings" in g.conventions

    def test_minimal_parse(self) -> None:
        profile = parse_reviewbot_md(MINIMAL_REVIEWBOT_MD)
        assert profile.platform_data.primary_language == "Go"
        assert profile.language_version is None
        assert profile.framework is None
        assert profile.package_manager is None
        assert profile.layout is None
        assert profile.automated_checks == AutomatedChecks()
        assert profile.guidance == ReviewGuidance()

    def test_empty_content(self) -> None:
        profile = parse_reviewbot_md("")
        assert profile.platform_data.primary_language == "Unknown"
        assert profile.language_version is None

    def test_missing_sections_tolerated(self) -> None:
        content = "# .reviewbot.md\n\n## Stack\n- **Language:** Rust 1.78\n"
        profile = parse_reviewbot_md(content)
        assert profile.platform_data.primary_language == "Rust"
        assert profile.language_version == "1.78"
        assert profile.automated_checks == AutomatedChecks()
        assert profile.guidance == ReviewGuidance()

    def test_extra_content_ignored(self) -> None:
        content = (
            "# .reviewbot.md\n\n"
            "Some intro text that should be ignored.\n\n"
            "## Stack\n"
            "- **Language:** TypeScript 5.4\n"
            "- **Unknown field:** whatever\n\n"
            "## Notes\n"
            "This section is unknown and should be skipped.\n"
        )
        profile = parse_reviewbot_md(content)
        assert profile.platform_data.primary_language == "TypeScript"
        assert profile.language_version == "5.4"

    def test_comma_separated_tools(self) -> None:
        content = (
            "## Stack\n- **Language:** Python\n\n"
            "## Automated Checks\n"
            "- **Linting:** ruff, pylint, flake8\n"
        )
        profile = parse_reviewbot_md(content)
        assert profile.automated_checks.linting == ("ruff", "pylint", "flake8")

    def test_skip_subsection_short_heading(self) -> None:
        """Parser also matches '### Skip' without the parenthetical."""
        content = (
            "## Stack\n- **Language:** Python\n\n"
            "## Review Guidance\n\n"
            "### Skip\n"
            "- Formatting issues\n"
        )
        profile = parse_reviewbot_md(content)
        assert "Formatting issues" in profile.guidance.skip_in_review


# ── TestGenerateReviewbotMd ──────────────────────────────────────────


class TestGenerateReviewbotMd:
    """Tests for generate_reviewbot_md."""

    def test_generates_header_comment(self) -> None:
        profile = _make_profile()
        md = generate_reviewbot_md(profile)
        assert "<!-- Auto-generated by AI ReviewBot" in md

    def test_generates_stack(self) -> None:
        profile = _make_profile(language_version="3.13", framework="Django 5.1")
        md = generate_reviewbot_md(profile)
        assert "- **Language:** Python 3.13" in md
        assert "- **Framework:** Django 5.1" in md

    def test_generates_automated_checks(self) -> None:
        profile = _make_profile(
            linting=("ruff",),
            formatting=("ruff format",),
        )
        md = generate_reviewbot_md(profile)
        assert "## Automated Checks" in md
        assert "- **Linting:** ruff" in md
        assert "- **Formatting:** ruff format" in md

    def test_generates_guidance(self) -> None:
        profile = _make_profile(
            skip=("Formatting",),
            focus=("Security",),
            conventions=("Conventional commits",),
        )
        md = generate_reviewbot_md(profile)
        assert "### Skip (CI handles these)" in md
        assert "- Formatting" in md
        assert "### Focus" in md
        assert "- Security" in md
        assert "### Conventions" in md
        assert "- Conventional commits" in md

    def test_omits_empty_sections(self) -> None:
        profile = _make_profile()
        md = generate_reviewbot_md(profile)
        assert "## Automated Checks" not in md
        assert "## Review Guidance" not in md

    def test_trailing_newline(self) -> None:
        profile = _make_profile()
        md = generate_reviewbot_md(profile)
        assert md.endswith("\n")

    def test_minimal_output(self) -> None:
        profile = _make_profile(primary_language="Go")
        md = generate_reviewbot_md(profile)
        assert "- **Language:** Go" in md
        assert "## Automated Checks" not in md


# ── Roundtrip ────────────────────────────────────────────────────────


class TestRoundtrip:
    """Roundtrip: generate -> parse -> compare."""

    def test_full_roundtrip(self) -> None:
        original = _make_profile(
            primary_language="Python",
            language_version="3.13",
            framework="Django 5.1",
            package_manager="uv",
            layout="src",
            linting=("ruff",),
            formatting=("ruff format",),
            type_checking=("mypy --strict",),
            testing=("pytest",),
            security=("bandit",),
            ci_provider="GitHub Actions",
            skip=("Code formatting",),
            focus=("Security",),
            conventions=("Conventional commits",),
        )
        md = generate_reviewbot_md(original)
        parsed = parse_reviewbot_md(md)

        assert parsed.platform_data.primary_language == "Python"
        assert parsed.language_version == "3.13"
        assert parsed.framework == "Django 5.1"
        assert parsed.package_manager == "uv"
        assert parsed.layout == "src"
        assert parsed.automated_checks.linting == ("ruff",)
        assert parsed.automated_checks.formatting == ("ruff format",)
        assert parsed.automated_checks.type_checking == ("mypy --strict",)
        assert parsed.automated_checks.testing == ("pytest",)
        assert parsed.automated_checks.security == ("bandit",)
        assert parsed.automated_checks.ci_provider == "GitHub Actions"
        assert parsed.guidance.skip_in_review == ("Code formatting",)
        assert parsed.guidance.focus_in_review == ("Security",)
        assert parsed.guidance.conventions == ("Conventional commits",)

    def test_minimal_roundtrip(self) -> None:
        original = _make_profile(primary_language="Rust")
        md = generate_reviewbot_md(original)
        parsed = parse_reviewbot_md(md)
        assert parsed.platform_data.primary_language == "Rust"
        assert parsed.language_version is None
        assert parsed.framework is None

    @pytest.mark.parametrize(
        "language_version",
        ["3.13", "22.x", "1.78.0", None],
    )
    def test_roundtrip_versions(self, language_version: str | None) -> None:
        original = _make_profile(language_version=language_version)
        md = generate_reviewbot_md(original)
        parsed = parse_reviewbot_md(md)
        assert parsed.language_version == language_version


# ── Helpers ──────────────────────────────────────────────────────────


def _make_profile(  # noqa: PLR0913
    *,
    primary_language: str = "Python",
    language_version: str | None = None,
    framework: str | None = None,
    package_manager: str | None = None,
    layout: str | None = None,
    checks: AutomatedChecks | None = None,
    guidance: ReviewGuidance | None = None,
    **kw: object,
) -> ProjectProfile:
    # Shorthand kwargs for checks/guidance when full objects are overkill
    if checks is None:
        checks = AutomatedChecks(
            linting=_tup(kw, "linting"),
            formatting=_tup(kw, "formatting"),
            type_checking=_tup(kw, "type_checking"),
            testing=_tup(kw, "testing"),
            security=_tup(kw, "security"),
            ci_provider=kw.get("ci_provider"),  # type: ignore[arg-type]
        )
    if guidance is None:
        guidance = ReviewGuidance(
            skip_in_review=_tup(kw, "skip"),
            focus_in_review=_tup(kw, "focus"),
            conventions=_tup(kw, "conventions"),
        )
    return ProjectProfile(
        platform_data=PlatformData(
            languages={primary_language: 100.0},
            primary_language=primary_language,
        ),
        language_version=language_version,
        framework=framework,
        package_manager=package_manager,
        layout=layout,
        automated_checks=checks,
        guidance=guidance,
    )


def _tup(kw: dict[str, object], key: str) -> tuple[str, ...]:
    val = kw.get(key, ())
    if isinstance(val, tuple):
        return val
    return ()  # pragma: no cover
