"""Unit tests for review formatter."""

from ai_reviewer.core.formatter import (
    RUSSIAN_DISCLAIMER,
    format_review_comment,
    is_russian_language,
)
from ai_reviewer.core.models import (
    ReviewResult,
    TaskAlignmentStatus,
    Vulnerability,
    VulnerabilitySeverity,
)


class TestFormatReviewComment:
    """Tests for format_review_comment function."""

    def test_format_clean_result(self) -> None:
        """Test formatting a result with no vulnerabilities."""
        result = ReviewResult(
            summary="Code looks good.",
            task_alignment=TaskAlignmentStatus.ALIGNED,
            task_alignment_reasoning="Matches requirements.",
        )

        comment = format_review_comment(result)

        assert "# AI Code Review Report" in comment
        assert "## Summary" in comment
        assert "Code looks good." in comment
        assert "## Security Analysis" in comment
        assert "✅ No critical vulnerabilities found." in comment
        assert "## Task Alignment" in comment
        assert "✅ Aligned" in comment
        assert "Matches requirements." in comment

    def test_format_vulnerabilities(self) -> None:
        """Test formatting a result with vulnerabilities."""
        vuln = Vulnerability(
            title="SQL Injection",
            description="Unsafe query",
            severity=VulnerabilitySeverity.CRITICAL,
            recommendation="Use params",
            file="db.py",
            line=10,
        )
        result = ReviewResult(
            summary="Found issues.",
            vulnerabilities=(vuln,),
            task_alignment=TaskAlignmentStatus.INSUFFICIENT_DATA,
        )

        comment = format_review_comment(result)

        assert "| Severity | Issue | Description | Recommendation |" in comment
        assert "🔴 **CRITICAL**" in comment
        assert "SQL Injection" in comment
        assert "Unsafe query" in comment
        assert "Use params" in comment
        assert "_File: db.py:10_" in comment
        assert "⚠️ Insufficient Data" in comment

    def test_format_misaligned_task(self) -> None:
        """Test formatting a misaligned task result."""
        result = ReviewResult(
            summary="Logic error.",
            task_alignment=TaskAlignmentStatus.MISALIGNED,
            task_alignment_reasoning="Does not implement feature X.",
        )

        comment = format_review_comment(result)

        assert "❌ Misaligned" in comment
        assert "Does not implement feature X." in comment

    def test_escape_pipes_in_table(self) -> None:
        """Test that pipes in content are escaped to preserve table structure."""
        vuln = Vulnerability(
            title="Issue | with pipe",
            description="Desc | pipe",
            severity=VulnerabilitySeverity.LOW,
            recommendation="Fix | pipe",
        )
        result = ReviewResult(vulnerabilities=(vuln,))

        comment = format_review_comment(result)

        assert "Issue \\| with pipe" in comment
        assert "Desc \\| pipe" in comment
        assert "Fix \\| pipe" in comment

    def test_russian_language_includes_disclaimer(self) -> None:
        """Test that Russian language reviews include the disclaimer."""
        result = ReviewResult(
            summary="Код выглядит хорошо.",
            task_alignment=TaskAlignmentStatus.ALIGNED,
        )

        comment = format_review_comment(result, language="ru")

        assert RUSSIAN_DISCLAIMER in comment
        assert "Слава Украине!" in comment

    def test_russian_language_rus_code_includes_disclaimer(self) -> None:
        """Test that 'rus' (ISO 639-3) language code also includes disclaimer."""
        result = ReviewResult(
            summary="Код выглядит хорошо.",
            task_alignment=TaskAlignmentStatus.ALIGNED,
        )

        comment = format_review_comment(result, language="rus")

        assert RUSSIAN_DISCLAIMER in comment

    def test_non_russian_language_no_disclaimer(self) -> None:
        """Test that non-Russian languages don't include the disclaimer."""
        result = ReviewResult(
            summary="Code looks good.",
            task_alignment=TaskAlignmentStatus.ALIGNED,
        )

        for lang in ["en", "uk", "de", "fr", "es", None]:
            comment = format_review_comment(result, language=lang)
            assert RUSSIAN_DISCLAIMER not in comment

    def test_disclaimer_appears_before_footer(self) -> None:
        """Test that disclaimer appears before the footer."""
        result = ReviewResult(
            summary="Test.",
            task_alignment=TaskAlignmentStatus.ALIGNED,
        )

        comment = format_review_comment(result, language="ru")

        disclaimer_pos = comment.find("Слава Украине!")
        footer_pos = comment.find("Generated by AI Code Reviewer")
        assert disclaimer_pos < footer_pos


class TestIsRussianLanguage:
    """Tests for is_russian_language function."""

    def test_ru_is_russian(self) -> None:
        """Test that 'ru' is detected as Russian."""
        assert is_russian_language("ru") is True

    def test_rus_is_russian(self) -> None:
        """Test that 'rus' (ISO 639-3) is detected as Russian."""
        assert is_russian_language("rus") is True

    def test_case_insensitive(self) -> None:
        """Test that detection is case-insensitive."""
        assert is_russian_language("RU") is True
        assert is_russian_language("Ru") is True
        assert is_russian_language("RUS") is True

    def test_non_russian_languages(self) -> None:
        """Test that other languages are not detected as Russian."""
        assert is_russian_language("en") is False
        assert is_russian_language("uk") is False
        assert is_russian_language("de") is False
        assert is_russian_language("fr") is False

    def test_none_is_not_russian(self) -> None:
        """Test that None is not detected as Russian."""
        assert is_russian_language(None) is False

    def test_empty_string_is_not_russian(self) -> None:
        """Test that empty string is not detected as Russian."""
        assert is_russian_language("") is False
